version: '2'

services:
    apache:
        build: pdf-server
        image: goldy/pdf-server
        command:
            - apache2
            - -DFOREGROUND
        extends:
            service: auth
            file: meta.yml
        volumes_from:
            - index
        expose:
            - 80
        environment:
            ENTRYPOINT_CONFIG: entrypoint-apache.yml
        restart: always

    index:
        build: pdf-server
        image: goldy/pdf-server
        command:
            - xapian-update
        environment:
            ENTRYPOINT_CONFIG: entrypoint-update.yml
            ENTRYPOINT_USER: 33
        extends:
            service: meta
            file: meta.yml
        restart: on-failure

    ocr:
        build: pdf-server
        image: goldy/pdf-server
        command:
            - run-ocr
        environment:
            ENTRYPOINT_CONFIG: entrypoint-ocr.yml
            ENTRYPOINT_USER: 33
        extends:
            service: lang
            file: meta.yml
        restart: on-failure

    sync:
        image: goldy/syncthing
        environment:
            ENTRYPOINT_USER: 33
        volumes:
            - pdf-files:/var/syncthing/documents/
        restart: always

    tor:
        image: goldy/tor-hidden-service
        links:
            - apache
            - sync
        environment:
            APACHE_PORTS: 80:80
            SYNC_PORTS: 80:8384
        volumes:
            - tor-keys:/var/lib/tor
        restart: on-failure


volumes:
    pdf-files:
        driver: local
    tor-keys:
        driver: local
